### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by oppenheimer-** [JoseConseco/texture_synthesis#1]
This is run in Blender 2.8 on Windows 10 Home.

There are path errors due to double slashes:

```
['D:\\Programme\\texture-synthesis-0.6.0-x86_64-pc-windows-msvc\\texture-synthesis.exe', '--out', 'C:\\tmp\\Generated.png', '--out-size', '512x512', '--seed', '1', '--rand-init', '1', '--k-neighs', '50', '--cauchy', '1.0', '--backtrack-pct', '0.5', '--backtrack-stages', '5', '--in-size', '512x512', '--tiling', 'generate', '']
[31merror[0m: Das System kann den angegebenen Pfad nicht finden. (os error 3)
Waited 30 sec for C:\tmp\Generated.png to be generated, no output detected. Time passed: 2e+09 sec
Skipping loading generated file
```

**Comment by JoseConseco** [comment]
I do not see double slashes in your  report anywhere... and it looks like there is no input image paramerter - > the last string after 'generate' - is  '.' - but it should be path to input image.

**Comment by oppenheimer-** [comment]
Sorry, didn't mark it as "code"... the double slashes are not a problem.
Nevermind, i expected the synthesis to be run on the image in the viewer. My bad!
